### ISSUE TITLE
buildpack should support port config defined in "Passengerfile.json"

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/passenger#6]
When I define a Passengerfile.json with a port specified, the app image built from Passenger Buildpack still defaults to port `3000` when `PORT` environment variable isn't set.

```
cat Passengerfile.json
{
  "engine": "builtin",
  "environment": "development",
  "port": 4000
}
...
docker run -p 4000:4000 rails-passenger-builtin
 --> Downloading a Phusion Passenger agent binary for your platform
--------------------------
 [passenger_native_support.so] trying to compile for the current user (vcap) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Compilation successful. The logs are here:
     /tmp/passenger_native_support-wszuiu.log
 [passenger_native_support.so] successfully loaded.
=============== Phusion Passenger Standalone web server started ===============
PID file: /workspace/tmp/pids/passenger.3000.pid
Log file: /workspace/log/passenger.3000.log
Environment: development
Accessible via: http://0.0.0.0:3000/
```

**Expected Behavior**
Port defined in `Passengerfile.json` should take precedence over buildpack default (3000)

**Comment by robdimsdale** [comment]
@paketo-buildpacks/ruby-maintainers I'm happy to pick this up. Please assign it to me (and add it to the [workstreams](https://github.com/orgs/paketo-buildpacks/projects/20) project).

I think we would do something like parse the `Passengerfile.json` for the `port` field, and if it exists we can select it instead of the default port in [`build.go`](https://github.com/paketo-buildpacks/passenger/blob/b4ba149ec12ab1e979cb3bc9c5ffd9e841be6292/build.go#L50). Sound about right?

**Comment by robdimsdale** [comment]
Right, because passenger would look for its own config file at startup, and parse the port from there.

I was thinking about how the [rackup buildpack does this](https://github.com/paketo-buildpacks/rackup/blob/70d4a82348856c56de5dec0a335ca007b41781e5/build.go#L39-L46) and forgetting that passenger might be simpler.

**Comment by robdimsdale** [comment]
As I start to explore this, I think there are three ways a port can be defined. They are as follows (in priority order):
1. At runtime with the `PORT` environment variable
2. In the `Passengerfile.json` config file
3. A default value of `3000` hard-coded in the buildpack

Currently we support cases 1) and 3), and I think we should continue to support them with the current priority (i.e. `PORT` environment variable takes precedence over the default value of `3000`).

In order to add case 2) and still support the existing priorities and behavior, I think we need to explicitly parse the port out of the `Passengerfile.json` and provide it to the start command. This is essentially the [same behavior that we see in rackup](https://github.com/paketo-buildpacks/rackup/blob/70d4a82348856c56de5dec0a335ca007b41781e5/build.go#L39-L46).

Does this make sense? Am I missing a simpler way to support the existing behavior/priorities while also adding the new feature?

**Comment by ryanmoran** [comment]
No. I don't think there is anything easier. If we want to support cases 1 and 2 at runtime, then we'd likely need to do what you are suggesting, or use something more complicated like `exec.d`. I think, with those tradeoffs, the path you've outlined seems reasonable.
